name: Coverage

on:
  pull_request:
    branches:
      - 'main'

env:
  CI: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Calculate Code Coverage
        run: npm run ci:coverage
